const dotenv = require('dotenv');
const path = require("path");

// Load environment variables from specific file
dotenv.config({ path: `.env.${process.env.NODE_ENV || 'local'}` });

module.exports = {
    AUTHENTICATION_SERVICE_DATABASE_URL: process.env.AUTHENTICATION_SERVICE_DATABASE_URL,
    AUTHENTICATION_SERVICE_ADDRESS: process.env.AUTHENTICATION_SERVICE_ADDRESS,
    AUTHENTICATION_SERVICE_DEFAULT_LANGUAGE: process.env.AUTHENTICATION_SERVICE_DEFAULT_LANGUAGE,
    AUTHENTICATION_SERVICE_AUTH_SECRET_KEY: process.env.AUTHENTICATION_SERVICE_AUTH_SECRET_KEY,
    AUTHENTICATION_SERVICE_AUTH_TOKEN_EXPIRE_TIME: process.env.AUTHENTICATION_SERVICE_AUTH_TOKEN_EXPIRE_TIME,
    AUTHENTICATION_SERVICE_RESET_PASSWORD_SECRET_KEY: process.env.AUTHENTICATION_SERVICE_RESET_PASSWORD_SECRET_KEY,
    AUTHENTICATION_SERVICE_RESET_PASSWORD_TOKEN_EXPIRE_TIME: process.env.AUTHENTICATION_SERVICE_RESET_PASSWORD_TOKEN_EXPIRE_TIME,
    AUTHENTICATION_SERVICE_INVITATION_SECRET_KEY: process.env.AUTHENTICATION_SERVICE_INVITATION_SECRET_KEY,
    AUTHENTICATION_SERVICE_INVITATION_TOKEN_EXPIRE_TIME: process.env.AUTHENTICATION_SERVICE_INVITATION_TOKEN_EXPIRE_TIME,
    AUTHENTICATION_SERVICE_WEB_INVITATION_URL: process.env.AUTHENTICATION_SERVICE_WEB_INVITATION_URL,
    AUTHENTICATION_SERVICE_WEB_RESET_PASSWORD_URL: process.env.AUTHENTICATION_SERVICE_WEB_RESET_PASSWORD_URL,
    WEB_BASE_URL: process.env.WEB_BASE_URL,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_EMAIL: process.env.SMTP_EMAIL,
    SMTP_PASSWORD: process.env.SMTP_PASSWORD,
    SMTP_FROM_EMAIL: process.env.SMTP_FROM_EMAIL,
    ACTIVITY_LOGS_SERVICE_ADDRESS: process.env.ACTIVITY_LOGS_SERVICE_ADDRESS,
    AUTHENTICATION_SERVICE_PROTO_PATH: path.join(process.cwd(), `../proto-schemas/authentication-service`),
    ACTIVITY_LOGS_SERVICE_PROTO_PATH: path.join(process.cwd(), `../proto-schemas/activity-log-service`),
    PUBLIC_FOLDER_PATH: path.join(process.cwd(), "../public"),
    TEMP_FOLDER_PATH: "temporaries",
    TEMP_FOLDER_MAX_FILE_AGE_HOURS: process.env.TEMP_FOLDER_MAX_FILE_AGE_HOURS
};